"""Deutsche Abkürzungen für die Satzsegmentierung."""

from __future__ import annotations

__all__ = [
    "ABBREVIATIONS",
    "SENTENCE_END_ABBREVIATIONS",
    "is_abbreviation",
]

# Abkürzungen, nach denen ein Punkt keinen Satz beendet.
ABBREVIATIONS: frozenset[str] = frozenset(
    {
        "z. b.",
        "z.b.",
        "zb.",
        "d. h.",
        "d.h.",
        "u. a.",
        "u.a.",
        "u. ä.",
        "o. ä.",
        "o. g.",
        "s. o.",
        "s. u.",
        "vgl.",
        "bzw.",
        "usw.",
        "etc.",
        "evtl.",
        "ggf.",
        "inkl.",
        "exkl.",
        "zzgl.",
        "abzgl.",
        "ca.",
        "etwa",
        "dr.",
        "prof.",
        "prof. dr.",
        "dipl.-ing.",
        "dipl.",
        "ing.",
        "hr.",
        "hrn.",
        "fr.",
        "frn.",
        "gmbh",
        "mbh",
        "ag",
        "kg",
        "gbr",
        "e. v.",
        "e.v.",
        "e. k.",
        "ohg",
        "nr.",
        "nrn.",
        "art.",
        "abs.",
        "s.",
        "satz",
        "bd.",
        "kap.",
        "anl.",
        "anh.",
        "az.",
        "tel.",
        "fax",
        "mobil",
        "geb.",
        "gest.",
        "jh.",
        "jhd.",
        "mrd.",
        "mio.",
        "tsd.",
        "std.",
        "min.",
        "max.",
        "mwst.",
        "ust.",
        "ustg.",
        "ao.",
        "stgb.",
        "bgb.",
        "hgb.",
        "zpo.",
        "vob",
        "vob/b",
        "gmbhg",
        "gg",
        "ewr",
        "eu",
        "ezb",
        "bzgl.",
        "inkl",
        "zzgl",
        # Rechts- und Geschäftssprache
        "gem.",
        "ggü.",
        "sog.",
        "bspw.",
        "ff.",
        "i. d. r.",
        "i.d.r.",
        "i. v. m.",
        "i.v.m.",
        "i. h. v.",
        "i.h.v.",
        "i. s. d.",
        "i.s.d.",
        "z. zt.",
        "z.zt.",
        "zzt.",
        "z. t.",
        "z.t.",
        "m. e.",
        "m.e.",
        "m. w. n.",
        "m.w.n.",
        "s. a.",
        "s.a.",
        "u. u.",
        "u.u.",
        "u. e.",
        "u.e.",
        "n. f.",
        "n.f.",
        "a. f.",
        "a.f.",
        "lit.",
        "buchst.",
        "str.",
        "kfm.",
        "mtl.",
        "jhrl.",
        "tägl.",
        "techn.",
        "pers.",
        "schriftl.",
        "telef.",
    }
)

# Abkürzungen, die am Satzende stehen können und dann einen Satz beenden.
SENTENCE_END_ABBREVIATIONS: frozenset[str] = frozenset({"usw.", "etc.", "u. a.", "u.a."})


def is_abbreviation(token: str) -> bool:
    """Prüft, ob ein Token eine bekannte Abkürzung ist.

    Groß- und Kleinschreibung spielen keine Rolle.
    """
    return token.strip().lower() in ABBREVIATIONS
