"""Deutsche Abkürzungen für die Satzsegmentierung.

Die Listen stammen aus zwei Quellen:

- Duden, Rechtschreibregeln, Abschnitt D 4: Steht eine Abkürzung mit Punkt am
  Satzende, ist der Abkürzungspunkt zugleich der Schlusspunkt des Satzes.
  Daraus folgt ``SENTENCE_END_ABBREVIATIONS``.
- Wikipedia, Portal:Abkürzungen/Gebräuchliche Abkürzungen, Teil 1 (mit Punkt).

Grundsatz bei der Auswahl: Fehlt eine Abkürzung, zerreißt die Segmentierung
einen Satz mitten im Satz — das ist der teure Fehler. Steht eine zu viel in der
Liste, bleiben zwei Sätze zusammen — das ist der billige Fehler. Die Liste ist
deshalb bewusst großzügig.

Nicht aufgenommen sind Abkürzungen, die zugleich deutsche Wortformen sind
(``dies.``, ``den.``, ``dass.``). Sie würden echte Satzenden verschlucken.
"""

from __future__ import annotations

__all__ = [
    "ABBREVIATIONS",
    "SENTENCE_END_ABBREVIATIONS",
    "is_abbreviation",
]

# Abkürzungen, nach denen ein Punkt keinen Satz beendet.
ABBREVIATIONS: frozenset[str] = frozenset(
    {
        # --- Allgemein ---
        "z. b.",
        "z.b.",
        "zb.",
        "d. h.",
        "d.h.",
        "d. i.",
        "d.i.",
        "u. a.",
        "u.a.",
        "u. ä.",
        "u.ä.",
        "o. ä.",
        "o.ä.",
        "o. g.",
        "o.g.",
        "s. o.",
        "s.o.",
        "s. u.",
        "s.u.",
        "s. a.",
        "s.a.",
        "s. d.",
        "s.d.",
        "s. z.",
        "s. v. w.",
        "svw.",
        "vgl.",
        "bzw.",
        "bezw.",
        "usw.",
        "usf.",
        "etc.",
        "evtl.",
        "ggf.",
        "ggü.",
        "inkl.",
        "exkl.",
        "einschl.",
        "ausschl.",
        "zzgl.",
        "abzgl.",
        "ca.",
        "rd.",
        "resp.",
        "sog.",
        "bspw.",
        "dgl.",
        "desgl.",
        "ebd.",
        "ehem.",
        "ehemal.",
        "eig.",
        "eigtl.",
        "entspr.",
        "erg.",
        "frdl.",
        "geb.",
        "gegr.",
        "geh.",
        "gek.",
        "gesch.",
        "gest.",
        "gez.",
        "hg.",
        "lt.",
        "urspr.",
        "verh.",
        "verw.",
        "vorm.",
        "zus.",
        "zw.",
        "z. zt.",
        "z.zt.",
        "zzt.",
        "zz.",
        "z. t.",
        "z.t.",
        "z. z.",
        "z. d. a.",
        "z. h.",
        "z. hd.",
        "b. w.",
        "dto.",
        "id.",
        "bzgl.",
        "bes.",
        "allg.",
        "spez.",
        "spec.",
        "pers.",
        "techn.",
        "schriftl.",
        "telef.",
        "amtl.",
        "anerk.",
        "angew.",
        "anschl.",
        "anon.",
        "apl.",
        "asym.",
        "asymp.",
        "attr.",
        "aufg.",
        "aufkl.",
        "beil.",
        "brosch.",
        "kart.",
        "kath.",
        "kgl.",
        "led.",
        "luth.",
        "math.",
        "möbl.",
        "nachm.",
        "ärztl.",
        # --- Titel und Anreden ---
        "dr.",
        "prof.",
        "prof. dr.",
        "dipl.",
        "dipl.-ing.",
        "dr.-ing.",
        "ing.",
        "hr.",
        "hrn.",
        "fr.",
        "frn.",
        "frhr.",
        "frl.",
        "st.",
        "skt.",
        "pfr.",
        "exz.",
        "dres.",
        "jr.",
        "jun.",
        "sen.",
        "ph.d.",
        "verf.",
        "vf.",
        "vors.",
        "hs.",
        "ms.",
        "mskr.",
        # --- Rechtsformen ---
        "gmbh",
        "mbh",
        "ag",
        "kg",
        "gbr",
        "ohg",
        "e. v.",
        "e.v.",
        "e. k.",
        "e.k.",
        "e. g.",
        "ev.",
        "ges.",
        # --- Gliederung und Verweise ---
        "nr.",
        "nrn.",
        "no.",
        "nos.",
        "art.",
        "artt.",
        "art.-nr.",
        "abs.",
        "s.",
        "satz",
        "bd.",
        "bde.",
        "kap.",
        "anl.",
        "anh.",
        "ahg.",
        "bl.",
        "abb.",
        "abf.",
        "abk.",
        "abz.",
        "anm.",
        "ann.",
        "anz.",
        "aufl.",
        "ausg.",
        "best.-nr.",
        "betr.",
        "bez.",
        "ff.",
        "fig.",
        "forts.",
        "jg.",
        "jh.",
        "jhd.",
        "jahrh.",
        "kl.",
        "kr.",
        "lfg.",
        "lfrg.",
        "pkt.",
        "pos.",
        "tab.",
        "teilbd.",
        "vers.",
        "ziff.",
        "zit.",
        "ztschr.",
        "ztg.",
        "op.",
        "sp.",
        "verl.",
        "gew.",
        "expl.",
        "ex.",
        "komp.",
        "prov.",
        "rel.",
        "reg.-bez.",
        "sa.",
        "stud.",
        "gr.tr.",
        # --- Recht und Verwaltung ---
        "gem.",
        "az.",
        "aktz.",
        "anr.",
        "rn.",
        "rz.",
        "randnr.",
        "a. a. o.",
        "a.a.o.",
        "a. d.",
        "a. g.",
        "a. gl. o.",
        "a. s.",
        "a. a. s.",
        "a. d. hrsg.",
        "a. d. ü.",
        "i. d. r.",
        "i.d.r.",
        "i. v. m.",
        "i.v.m.",
        "i. h. v.",
        "i.h.v.",
        "i. s. d.",
        "i.s.d.",
        "i. e. s.",
        "i.e.s.",
        "i. e.",
        "i. j.",
        "i. r.",
        "i. s.",
        "i. v.",
        "i. z. m.",
        "m. e.",
        "m.e.",
        "m. w.",
        "m. w. n.",
        "m.w.n.",
        "m. a. n.",
        "m. a. w.",
        "m. d. b.",
        "u. u.",
        "u.u.",
        "u. e.",
        "u.e.",
        "u. w.",
        "u. d. m.",
        "u. dgl.",
        "u. ü. v.",
        "u. v. a.",
        "u. v. m.",
        "u. a. m.",
        "u. A. w. g.",
        "n. f.",
        "n.f.",
        "a. f.",
        "a.f.",
        "n. chr.",
        "n.chr.",
        "v. chr.",
        "v.chr.",
        "n. j.",
        "n. m.",
        "v. j.",
        "v. m.",
        "o. j.",
        "o. b.",
        "o. p.",
        "o. b. d. a.",
        "p. a.",
        "q. e. d.",
        "v. a.",
        "v. g. u.",
        "v. h.",
        "v. t.",
        "w. o.",
        "lit.",
        "buchst.",
        "halbs.",
        "var.",
        "h. l.",
        "hl.",
        "str.",
        "kfm.",
        "lfd.",
        "lfd. nr.",
        "lfd. m.",
        "f. d. r.",
        "ges. gesch.",
        "c. t.",
        "s. t.",
        # --- Wirtschaft und Finanzen ---
        "mrd.",
        "md.",
        "mia.",
        "mio.",
        "mill.",
        "tsd.",
        "std.",
        "min.",
        "max.",
        "mwst.",
        "ust.",
        "ustg.",
        "pfd.",
        "pf.",
        "ztr.",
        "dz.",
        "bil.",
        "kto.",
        "spk.",
        "hbf.",
        "bhf.",
        "gbf.",
        "gmbhg",
        "mtl.",
        "jhrl.",
        "tägl.",
        # --- Gesetze und Normen ---
        "ao.",
        "stgb.",
        "stpo.",
        "bgb.",
        "hgb.",
        "zpo.",
        "stvo.",
        "vob",
        "vob/b",
        "gg",
        "ewr",
        "eu",
        "ezb",
        "din",
        "iso",
        # --- Sprache und Herkunft ---
        "dt.",
        "dtsch.",
        "engl.",
        "frz.",
        "grch.",
        "griech.",
        "ital.",
        "lat.",
        "nlat.",
        "russ.",
        "span.",
        "ahd.",
        "hd.",
        "hdt.",
        "frühnhd.",
        "idg.",
        "indog.",
        "indogerm.",
        "mhd.",
        # --- Fahrzeuge und Technik ---
        "kfz.",
        "sd.kfz.",
    }
)

# Abkürzungen, die am Satzende stehen können. Nach Duden D 4 ist ihr Punkt dann
# zugleich der Schlusspunkt des Satzes: „… Zitate von Goethe, Schiller u. a.
# Ihr Vater ist Regierungsrat a. D.“
#
# Ob wirklich ein Satzende vorliegt, entscheidet der Satzanfang danach. Steht
# dort ein Inhaltswort, geht die Aufzählung weiter („… u. a. Personen“); steht
# dort ein Funktionswort, beginnt ein neuer Satz. Siehe ``segment.py``.
SENTENCE_END_ABBREVIATIONS: frozenset[str] = frozenset(
    {
        "usw.",
        "usf.",
        "etc.",
        "u. a.",
        "u.a.",
        "u. ä.",
        "u.ä.",
        "o. ä.",
        "o.ä.",
        "u. a. m.",
        "u. v. a.",
        "u. v. m.",
        "dgl.",
        "desgl.",
        "ebd.",
        "ff.",
        "v. chr.",
        "v.chr.",
        "n. chr.",
        "n.chr.",
    }
)


def is_abbreviation(token: str) -> bool:
    """Prüft, ob ein Token eine bekannte Abkürzung ist.

    Groß- und Kleinschreibung spielen keine Rolle.
    """
    return token.strip().lower() in ABBREVIATIONS
